### PR TITLE
v8

### PR DESCRIPTION
**Pull request by cyrilletuzi**
Tracking changes in v8.

This is an important release, so beta testing is very welcomed:
```
npm install @ngx-pwa/local-storage@next
```

**DO NOT USE THIS IN PRODUCTION** as:
- API can still change at any time,
- there are important changes needing a lot of testing to be sure there is no loss of previously stored data.

You can need Angular 8 to test.

**The important thing to check is that previously stored data from version <= 7 is not lost when migrating to v8.**

Documentation:
- [Changelog](https://github.com/cyrilletuzi/angular-async-local-storage/blob/v8beta/CHANGELOG.md)
- [Migration guide](https://github.com/cyrilletuzi/angular-async-local-storage/blob/v8beta/docs/MIGRATION_TO_V8.md)
- [New validation guide](https://github.com/cyrilletuzi/angular-async-local-storage/blob/v8beta/docs/VALIDATION.md)
- [New interoperability guide](https://github.com/cyrilletuzi/angular-async-local-storage/blob/v8beta/docs/INTEROPERABILITY.md)

### CODE REVIEW

**Comment by cyrilletuzi** [comment]
@juristr @alexpanov @nikolalukovic @dherges @FrankiePo @beeman @joeskeen @rajd90 @alignsoft @sylvaingirardbe @darthmolen @feldmarv @doughlass @hannesrohde @venoby @supdegrave @LowieDelneste @Pato91 @elkozmon @pinalbhatt @todian @palmtreefrb @atiris @Gorniv @glebmachine @zhrichard @tluckett77 @diosney @Ruluk @rfcheung @marcstee

Hi everyone, as users of the lib, your help would be very welcomed.

I won't feel confident to go stable with this release if I'm the only one testing, as I've nearly recode everything in the lib.

**Comment by juristr** [comment]
@cyrilletuzi Sorry for not being responsive at all, but I'm not using the library right not in the project I'm currently working on. Used it in another project but unfortunately I have not the time right now to properly dive in and check the new version against it, sorry.

Maybe someone of the other mentioned ppl can jump in and help, also because your lib really useful. thx for doing all the hard work 👏

**Comment by cyrilletuzi** [comment]
@juristr Thanks for taking time for the feedback, I really appreciate it. 👍

**Comment by rfcheung** [comment]
I agree with @juristr. Very useful library!
I'm also working on another project, so haven't got the time yet.
I'll try to test it this weekend.

**Comment by rfcheung** [comment]
Finally had a moment to test the v8, things are looking good, no erros, tests are passing 👍

**Comment by cyrilletuzi** [comment]
@rfcheung Thanks you for your help. 👍

**Pull request merged**
