### PR TITLE
Added repository service

### PR DESCRIPTION
**Pull request by nikolalukovic**
Added a repository that wraps around async local storage to provide access to data as if it was a collection.
It provides both observables and promises.

### CODE REVIEW

**Comment by cyrilletuzi** [comment]
Thanks for your contribution, but could you explain a little more your intention and use cases ?

If I understand well, there are two propositions in this PR : 

1. Promises : not sure I want to allow that. This is an Angular-specific lib, and Angular standard for async is Observable. See this [comment](https://github.com/cyrilletuzi/angular-async-local-storage/issues/5#issuecomment-301078798). What is the specific reason/use case you propose that for ?

2. Collections : this is an interesting idea, but is it the role of this lib ? If the data stored is an array or any collection, there is already a lot of native functions or other librairies (including RxJS) to easily manage collections. Not sure we have to duplicate that in this lib. What is the specific reason/use case you propose that for ?

**Comment by nikolalukovic** [comment]
Hi,

I had a need on my project to hold data and regularly query them from indexed-db/local storage. So i used your lib to access them, and made a wrapper around which allows me to treat it as if it was a repository. I made a wrapper like this to simplify the use as much as possible.

I've added both promises and observables just because of ease of use. I'll remove them if you think they don't fit the criteria of this lib.

I reckoned it was a better idea to just extend this lib than to create a separate package since it's used to just access data, and this wrapper does the same but with added functionality.

Concerning the tests, I've tried to port spec files from my project here but was getting some weird errors and just couldn't figure out how to fix them. I was hoping for you to help me and create them if you still want to accept this pr.

**Comment by cyrilletuzi** [comment]
For the promises, if there is no specific use case, they won't fit in this lib. Going away from common Angular practices with no real reason would just complicate the maintenance of the lib.

For the collections, I need to think more about it. But first I need to finish the current beta feature (JSON validation), and the next release will also allow easier extensibility of this lib, which could be useful for this kind of PR. So I'll just ask you to wait a little.

About the tests, what are the errors ?

**Comment by cyrilletuzi** [comment]
Closing this, as there is no news, and the PR is out of scope of this lib. But thanks for the proposition.

**Pull request closed without merging**
